"""add room_type column to tenants

Revision ID: add_room_type_001
Revises: 47f9a953215f
Create Date: 2026-01-16 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_room_type_001'
down_revision = '47f9a953215f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('room_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'room_type')
    # ### end Alembic commands ###
